export const UTILS_MESSAGES = {
  PAGE_MUST_BE_AN_INTEGER: 'Page phải là một số nguyên.',
  PAGE_MUST_BE_GREATER_THAN_ZERO: 'Page phải lớn hơn 0.',
  LIMIT_MUST_BE_AN_INTEGER: 'Limit phải là một số nguyên.',
  LIMIT_MUST_BE_GREATER_THAN_OR_EQUAL_ZERO: 'Limit phải là một số lớn hơn hoặc bằng 0.',
  PERMISSION_DENIED: 'Quyền truy cập API bị từ chối.',
  IMAGE_ID_IS_REQUIRED: 'ID hình ảnh là bắt buộc',
  IMAGE_ID_IS_INVALID: 'ID hình ảnh không hợp lệ.'
} as const

export const USERS_MESSAGES = {
  REGISTER_SUCCESS: 'Đăng ký tài khoản thành công.',
  EMAIL_IS_REQUIRED: 'Email là bắc buộc.',
  EMAIL_IS_INVALID: 'Email không hợp lệ.',
  EMAIL_ALREADY_EXIST: 'Email đã tồn tại.',
  PASSWORD_IS_REQUIRED: 'Mật khẩu là bắt buộc.',
  PASSWORD_LENGTH_INVALID: 'Mật khẩu phải dài từ 8 đến 32 ký tự.',
  PASSWORD_IS_NOT_STRONG_ENOUGH:
    'Mật khẩu phải có ít nhất 1 ký tự viết thường, 1 ký tự viết hoa, 1 chữ số và 1 ký tự đặc biệt.',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Nhập lại mật khẩu là bắc buộc.',
  CONFIRM_PASSWORD_IS_NOT_MATCH: 'Nhập lại mật khẩu không chính xác.',
  ROLE_IS_REQUIRED: 'Vai trò người dùng là bắt buộc.',
  ROLE_IS_INVALID: 'Vai trò người dùng không hợp lệ,',
  VERIFY_EMAIL_SUCCESS: 'Xác minh email thành công.',
  VERIFY_EMAIL_TOKEN_IS_REQUIRED: 'Verify email token là băc buộc.',
  VERIFY_EMAIL_TOKEN_NOT_EXIST: 'Verify email token không tồn tại.',
  INVALID_EMAIL_OR_PASSWORD: 'Email hoặc mật khẩu không chính xác.',
  LOGIN_SUCCESS: 'Đăng nhập thành công.',
  LOGOUT_SUCCESS: 'Đăng xuất thành công.',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắc buộc.',
  REFRESH_TOKEN_DOES_NOT_EXIST: 'Refresh token không tồn tại.',
  REFRESH_TOKEN_SUCCESS: 'Refresh token thành công.',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc.',
  GET_PROFILE_ME_SUCCESS: 'Lấy hồ sơ của tôi thành công.',
  UPDATE_ME_SUCCESS: 'Cập nhật tài khoản của tôi thành công.',
  FULLNAME_IS_REQUIRED: 'Họ tên là bắt buộc',
  FULLNAME_LENGTH_IS_INVALID: 'Họ tên phải có độ dài từ 1 đến 50 ký tự.',
  AVATAR_ID_IS_INVALID: 'Avatar ID không hợp lệ.',
  CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công.',
  OLD_PASSWORD_IS_REQUIRED: 'Mật khẩu cũ là bắt buộc.',
  OLD_PASSWORD_IS_INVALID: 'Mật khẩu cũ không chính xác.',
  RESET_PASSWORD_REQUEST_SUCCESS: 'Yêu cầu đặt lại mật khẩu thành công, vui lòng kiểm tra hòm thư email bạn vừa nhập.',
  EMAIL_DOES_NOT_EXIST: 'Email không tồn tại trên hệ thống.',
  RESET_PASSWORD_SUCCESS: 'Đặt lại mật khẩu thành công.',
  RESET_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token là bắt buộc.',
  FORGOT_PASSWORD_TOKEN_DOES_NOT_EXIST: 'Forgot password token không tồn tại.',
  GET_ALL_USERS_SUCCESS: 'Lấy danh sách tất cả người dùng thành công.',
  USER_ID_IS_REQUIRED: 'ID người dùng là bắt buộc.',
  USER_ID_IS_INVALID: 'ID người dùng không hợp lệ,',
  USER_NOT_FOUND: 'Không tìm thấy người dùng.',
  UNVERIFIED_USER: 'Người dùng chưa được xác minh,',
  INACTIVE_USER: 'Người dùng không hoạt động.',
  UPDATE_USER_SUCCESS: 'Cập nhật người dùng thành công.',
  STATUS_IS_INVALID: 'Trạng thái người dùng không hợp lệ.',
  DELETE_USER_SUCCESS: 'Xóa người dùng thành công.'
} as const

export const MEDIAS_MESSAGES = {
  IMAGE_FILE_TYPE_INVALID: 'Loại file ảnh không hợp lệ.',
  IMAGE_FIELD_IS_REQUIRED: 'Trường image là bắt buộc.',
  UPLOAD_IMAGE_SUCCEED: 'Tải ảnh lên thành công.',
  FILE_NOT_FOUND: 'Không tìm thấy file.'
} as const

export const PRODUCTS_MESSAGES = {
  CREATE_PRODUCT_CATEGORY_SUCCESS: 'Tạo danh mục sản phẩm thành công.',
  PRODUCT_CATEGORY_NAME_IS_REQUIRED: 'Tên danh mục sản phẩm là bắt buộc.',
  UPDATE_PRODUCT_CATEGORY_SUCCESS: 'Cập nhật danh mục sản phẩm thành công.',
  PRODUCT_CATEGORY_ID_IS_REQUIRED: 'ID danh mục sản phẩm là bắt buộc.',
  PRODUCT_CATEGORY_ID_IS_INVALID: 'ID danh mục sản phẩm không hợp lệ.',
  PRODUCT_CATEGORY_NOT_EXIST: 'Danh mục sản phẩm không tồn tại.',
  DELETE_PRODUCT_CATEGORY_SUCCESS: 'Xóa danh mục sản phẩm thành công.',
  GET_PRODUCT_CATEGORIES_SUCCESS: 'Lấy danh sách danh mục sản phẩm thành công.',
  CREATE_BRAND_SUCCESS: 'Tạo nhãn hiệu sản phẩm thành công.',
  UPDATE_BRAND_SUCCESS: 'Cập nhật nhãn hiệu sản phẩm thành công.',
  DELETE_BRAND_SUCCESS: 'Xóa nhãn hiệu sản phẩm thành công.',
  GET_BRANDS_SUCCESS: 'Lấy danh sách nhãn hiệu sản phẩm thành công.',
  BRAND_ID_IS_REQUIRED: 'ID nhãn hiệu sản phẩm là bắt buộc.',
  BRAND_ID_IS_INVALID: 'ID nhãn hiệu sản phẩm không hợp lệ.',
  BRAND_NOT_EXIST: 'Nhãn hiệu sản phẩm không tồn tại.',
  BRAND_NAME_IS_REQUIRED: 'Tên nhãn hiệu sản phẩm là bắt buộc.',
  GET_PRODUCT_CATEGORY_SUCCESS: 'Lấy thông tin chi tiết danh mục sản phẩm thành công.',
  PRODUCT_PHOTOS_MUST_BE_AN_ARRAY: 'Hình ảnh sản phẩm phải là một mảng.',
  PRODUCT_PHOTOS_IS_INVALID: 'Hình ảnh sản phẩm không hợp lệ.',
  PRODUCT_NAME_IS_REQUIRED: 'Tên sản phẩm là bắt buộc.',
  PRODUCT_NAME_LENGTH_IS_INVALID: 'Tên sản phẩm phải có độ dài từ 10 đến 120 ký tự.',
  PRODUCT_DESCRIPTION_IS_REQUIRED: 'Mô tả sản phẩm là bắt buộc.',
  PRODUCT_DESCRIPTION_LENGTH_IS_INVALID: 'Mô tả sản phẩm phải có độ dài tối thiểu 100 ký tự.',
  PRODUCT_PRICE_IS_REQUIRED: 'Giá sản phẩm là bắt buộc.',
  PRODUCT_PRICE_MUST_BE_A_INT_GREATER_THAN_ZERO: 'Giá sản phẩm phải là một số nguyên dương lớn hơn không.',
  PRODUCT_VARIANTS_MUST_BE_AN_ARRAY: 'Biến thể sản phẩm phải là một mảng.',
  PRODUCT_VARIANTS_IS_INVALID: 'Biến thể sản phẩm không hợp lệ.',
  PRODUCT_VARIANTS_ITEM_MUST_BE_AN_OBJECT: 'Phần từ biến thể phải là một object.',
  PRODUCT_VARIANTS_ITEM_MUST_BE_A_STRING: 'Tên phần từ biến thể phải là một chuỗi.',
  CREATE_PRODUCT_SUCCESS: 'Tạo sản phẩm thành công.',
  UPDATE_PRODUCT_SUCCESS: 'Cập nhật sản phẩm thành công.',
  PRODUCT_ID_IS_REQUIRED: 'ID sản phẩm là bắt buộc.',
  PRODUCT_ID_IS_INVALID: 'ID sản phẩm không hợp lệ.',
  PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm.',
  PRODUCT_STATUS_IS_INVALID: 'Trạng thái sản phẩm không hợp lệ.',
  PRODUCT_APPROVAL_STATUS_IS_INVALID: 'Trạng thái phê duyệt sản phẩm không hợp lệ.',
  GET_PRODUCTS_SUCCESS: 'Lấy danh sách sản phẩm thành công.',
  GET_PRODUCT_SUCCESS: 'Lấy thông tin chi tiết sản phẩm thành công.'
} as const

export const ADDRESS_MESSAGES = {
  GET_PROVINCES_SUCCESS: 'Lấy danh sách tỉnh/thành thành công.',
  GET_DISTRICTS_SUCCESS: 'Lấy danh sách quận/huyện thành công.',
  PROVINCE_ID_IS_REQUIRED: 'ID tỉnh/thành là bắt buộc.',
  PROVINCE_ID_IS_INVALID: 'ID tỉnh/thành không hợp lệ.',
  PROVINCE_NOT_FOUND: 'Không tìm thấy tỉnh thành.',
  GET_WARDS_SUCCESS: 'Lấy danh sách phường xã thành công.',
  CREATE_ADDRESS_SUCCESS: 'Tạo địa chỉ mới thành công.',
  ADDRESS_FULLNAME_IS_REQUIRED: 'Họ tên người nhận là bắt buộc.',
  ADDRESS_PHONE_NUMBER_IS_REQUIRED: 'Số điện thoại người nhận là bắt buộc.',
  ADDRESS_PHONE_NUMBER_IS_INVALID: 'Số điện thoại người nhận không hợp lệ.',
  ADDRESS_DETAIL_IS_REQUIRED: 'Địa chỉ cụ thể là bắt buộc.',
  ADDRESS_TYPE_IS_REQUIRED: 'Loại địa chỉ là bắt buộc.',
  ADDRESS_TYPE_IS_INVALID: 'Loại địa chỉ không hợp lệ.',
  DISTRICT_ID_IS_REQUIRED: 'ID quận/huyện là bắt buộc.',
  WARD_ID_IS_REQUIRED: 'ID phường/xã là bắt buộc.',
  GET_MY_ADDRESSES_SUCCESS: 'Lấy danh sách địa chỉ của tôi thành công.',
  ADDRESS_ID_IS_REQUIRED: 'ID địa chỉ là bắt buộc.',
  ADDRESS_ID_IS_INVALID: 'ID địa chỉ không hợp lệ.',
  ADDRESS_NOT_FOUND: 'Không tìm thấy địa chỉ.',
  GET_ADDRESS_SUCCESS: 'Lấy thông tin địa chỉ thành công.',
  UPDATE_ADDRESS_SUCCESS: 'Cập nhật địa chỉ thành công.',
  DELETE_ADDRESS_SUCCESS: 'Xóa địa chỉ thành công.',
  SET_DEFAULT_ADDRESS_SUCCESS: 'Đặt địa chỉ mặc định thành công.'
} as const
