export const UTILS_MESSAGES = {
  PAGE_MUST_BE_AN_INTEGER: 'Page phải là một số nguyên.',
  PAGE_MUST_BE_GREATER_THAN_ZERO: 'Page phải lớn hơn 0.',
  LIMIT_MUST_BE_AN_INTEGER: 'Limit phải là một số nguyên.',
  LIMIT_MUST_BE_GREATER_THAN_OR_EQUAL_ZERO: 'Limit phải là một số lớn hơn hoặc bằng 0.',
  PERMISSION_DENIED: 'Quyền truy cập API bị từ chối.',
  IMAGE_ID_IS_REQUIRED: 'ID hình ảnh là bắt buộc',
  IMAGE_ID_IS_INVALID: 'ID hình ảnh không hợp lệ.'
} as const

export const USERS_MESSAGES = {
  REGISTER_SUCCESS: 'Đăng ký tài khoản thành công.',
  EMAIL_IS_REQUIRED: 'Email là bắc buộc.',
  EMAIL_IS_INVALID: 'Email không hợp lệ.',
  EMAIL_ALREADY_EXIST: 'Email đã tồn tại.',
  PASSWORD_IS_REQUIRED: 'Mật khẩu là bắt buộc.',
  PASSWORD_LENGTH_INVALID: 'Mật khẩu phải dài từ 8 đến 32 ký tự.',
  PASSWORD_IS_NOT_STRONG_ENOUGH:
    'Mật khẩu phải có ít nhất 1 ký tự viết thường, 1 ký tự viết hoa, 1 chữ số và 1 ký tự đặc biệt.',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Nhập lại mật khẩu là bắc buộc.',
  CONFIRM_PASSWORD_IS_NOT_MATCH: 'Nhập lại mật khẩu không chính xác.',
  ROLE_IS_REQUIRED: 'Vai trò người dùng là bắt buộc.',
  ROLE_IS_INVALID: 'Vai trò người dùng không hợp lệ,',
  VERIFY_EMAIL_SUCCESS: 'Xác minh email thành công.',
  VERIFY_EMAIL_TOKEN_IS_REQUIRED: 'Verify email token là băc buộc.',
  VERIFY_EMAIL_TOKEN_NOT_EXIST: 'Verify email token không tồn tại.',
  INVALID_EMAIL_OR_PASSWORD: 'Email hoặc mật khẩu không chính xác.',
  LOGIN_SUCCESS: 'Đăng nhập thành công.',
  LOGOUT_SUCCESS: 'Đăng xuất thành công.',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token là bắc buộc.',
  REFRESH_TOKEN_DOES_NOT_EXIST: 'Refresh token không tồn tại.',
  REFRESH_TOKEN_SUCCESS: 'Refresh token thành công.',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token là bắt buộc.',
  GET_PROFILE_ME_SUCCESS: 'Lấy hồ sơ của tôi thành công.',
  UPDATE_ME_SUCCESS: 'Cập nhật tài khoản của tôi thành công.',
  FULLNAME_IS_REQUIRED: 'Họ tên là bắt buộc',
  FULLNAME_LENGTH_IS_INVALID: 'Họ tên phải có độ dài từ 1 đến 50 ký tự.',
  AVATAR_ID_IS_INVALID: 'Avatar ID không hợp lệ.',
  CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công.',
  OLD_PASSWORD_IS_REQUIRED: 'Mật khẩu cũ là bắt buộc.',
  OLD_PASSWORD_IS_INVALID: 'Mật khẩu cũ không chính xác.',
  RESET_PASSWORD_REQUEST_SUCCESS: 'Yêu cầu đặt lại mật khẩu thành công, vui lòng kiểm tra hòm thư email bạn vừa nhập.',
  EMAIL_DOES_NOT_EXIST: 'Email không tồn tại trên hệ thống.',
  RESET_PASSWORD_SUCCESS: 'Đặt lại mật khẩu thành công.',
  RESET_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token là bắt buộc.',
  FORGOT_PASSWORD_TOKEN_DOES_NOT_EXIST: 'Forgot password token không tồn tại.',
  GET_ALL_USERS_SUCCESS: 'Lấy danh sách tất cả người dùng thành công.',
  USER_ID_IS_REQUIRED: 'ID người dùng là bắt buộc.',
  USER_ID_IS_INVALID: 'ID người dùng không hợp lệ,',
  USER_NOT_FOUND: 'Không tìm thấy người dùng.',
  UNVERIFIED_USER: 'Người dùng chưa được xác minh,',
  INACTIVE_USER: 'Người dùng không hoạt động.',
  UPDATE_USER_SUCCESS: 'Cập nhật người dùng thành công.',
  STATUS_IS_INVALID: 'Trạng thái người dùng không hợp lệ.',
  DELETE_USER_SUCCESS: 'Xóa người dùng thành công.'
} as const

export const MEDIAS_MESSAGES = {
  IMAGE_FILE_TYPE_INVALID: 'Loại file ảnh không hợp lệ.',
  IMAGE_FIELD_IS_REQUIRED: 'Trường image là bắt buộc.',
  UPLOAD_IMAGE_SUCCEED: 'Tải ảnh lên thành công.',
  FILE_NOT_FOUND: 'Không tìm thấy file.',
  GET_IMAGES_SUCCESS: 'Lấy danh sách hình ảnh thành công.',
  IMAGE_ID_IS_REQUIRED: 'ID hình ảnh là bắt buộc.',
  IMAGE_ID_IS_INVALID: 'ID hình ảnh không hợp lệ.',
  IMAGE_NOT_FOUND: 'Không tìm thấy hình ảnh.',
  DELETE_IMAGE_SUCCESS: 'Xóa hình ảnh thành công.'
} as const

export const PRODUCTS_MESSAGES = {
  CREATE_PRODUCT_CATEGORY_SUCCESS: 'Tạo danh mục sản phẩm thành công.',
  PRODUCT_CATEGORY_NAME_IS_REQUIRED: 'Tên danh mục sản phẩm là bắt buộc.',
  UPDATE_PRODUCT_CATEGORY_SUCCESS: 'Cập nhật danh mục sản phẩm thành công.',
  PRODUCT_CATEGORY_ID_IS_REQUIRED: 'ID danh mục sản phẩm là bắt buộc.',
  PRODUCT_CATEGORY_ID_IS_INVALID: 'ID danh mục sản phẩm không hợp lệ.',
  PRODUCT_CATEGORY_NOT_EXIST: 'Danh mục sản phẩm không tồn tại.',
  DELETE_PRODUCT_CATEGORY_SUCCESS: 'Xóa danh mục sản phẩm thành công.',
  GET_PRODUCT_CATEGORIES_SUCCESS: 'Lấy danh sách danh mục sản phẩm thành công.',
  CREATE_BRAND_SUCCESS: 'Tạo nhãn hiệu sản phẩm thành công.',
  UPDATE_BRAND_SUCCESS: 'Cập nhật nhãn hiệu sản phẩm thành công.',
  DELETE_BRAND_SUCCESS: 'Xóa nhãn hiệu sản phẩm thành công.',
  GET_BRANDS_SUCCESS: 'Lấy danh sách nhãn hiệu sản phẩm thành công.',
  BRAND_ID_IS_REQUIRED: 'ID nhãn hiệu sản phẩm là bắt buộc.',
  BRAND_ID_IS_INVALID: 'ID nhãn hiệu sản phẩm không hợp lệ.',
  BRAND_NOT_EXIST: 'Nhãn hiệu sản phẩm không tồn tại.',
  BRAND_NAME_IS_REQUIRED: 'Tên nhãn hiệu sản phẩm là bắt buộc.',
  GET_PRODUCT_CATEGORY_SUCCESS: 'Lấy thông tin chi tiết danh mục sản phẩm thành công.',
  PRODUCT_PHOTOS_MUST_BE_AN_ARRAY: 'Hình ảnh sản phẩm phải là một mảng.',
  PRODUCT_PHOTOS_IS_INVALID: 'Hình ảnh sản phẩm không hợp lệ.',
  PRODUCT_NAME_IS_REQUIRED: 'Tên sản phẩm là bắt buộc.',
  PRODUCT_NAME_LENGTH_IS_INVALID: 'Tên sản phẩm phải có độ dài từ 10 đến 120 ký tự.',
  PRODUCT_DESCRIPTION_IS_REQUIRED: 'Mô tả sản phẩm là bắt buộc.',
  PRODUCT_DESCRIPTION_LENGTH_IS_INVALID: 'Mô tả sản phẩm phải có độ dài tối thiểu 100 ký tự.',
  PRODUCT_PRICE_IS_REQUIRED: 'Giá sản phẩm là bắt buộc.',
  PRODUCT_PRICE_MUST_BE_A_INT_GREATER_THAN_ZERO: 'Giá sản phẩm phải là một số nguyên dương lớn hơn không.',
  PRODUCT_VARIANTS_MUST_BE_AN_ARRAY: 'Biến thể sản phẩm phải là một mảng.',
  PRODUCT_VARIANTS_IS_INVALID: 'Biến thể sản phẩm không hợp lệ.',
  PRODUCT_VARIANTS_ITEM_MUST_BE_AN_OBJECT: 'Phần từ biến thể phải là một object.',
  PRODUCT_VARIANTS_ITEM_MUST_BE_A_STRING: 'Tên phần từ biến thể phải là một chuỗi.',
  CREATE_PRODUCT_SUCCESS: 'Tạo sản phẩm thành công.',
  UPDATE_PRODUCT_SUCCESS: 'Cập nhật sản phẩm thành công.',
  PRODUCT_ID_IS_REQUIRED: 'ID sản phẩm là bắt buộc.',
  PRODUCT_ID_IS_INVALID: 'ID sản phẩm không hợp lệ.',
  PRODUCT_NOT_FOUND: 'Không tìm thấy sản phẩm.',
  PRODUCT_STATUS_IS_INVALID: 'Trạng thái sản phẩm không hợp lệ.',
  PRODUCT_APPROVAL_STATUS_IS_INVALID: 'Trạng thái phê duyệt sản phẩm không hợp lệ.',
  GET_PRODUCTS_SUCCESS: 'Lấy danh sách sản phẩm thành công.',
  GET_PRODUCT_SUCCESS: 'Lấy thông tin chi tiết sản phẩm thành công.',
  GET_ALL_PRODUCTS_SUCCESS: 'Lấy danh sách tất cả sản phẩm thành công.',
  DELETE_PRODUCT_SUCCESS: 'Xóa sản phẩm thành công.',
  ORDER_BY_IS_INVALID: 'Sắp xếp theo thứ tự không hợp lệ.',
  IS_FLASH_SALE_IS_INVALID: 'Is flash sale phải là boolean.',
  IS_ACTIVE_IS_INVALID: 'Trạng thái hoạt động phải là boolean.',
  MIN_PRICE_MUST_BE_AN_INT_GREATER_THAN_ZERO: 'Giá tối thiểu phải là một số nguyên lớn hơn 0.',
  MAX_PRICE_MUST_BE_AN_INT_GREATER_THAN_ZERO: 'Giá tối đa phải là một số nguyên lớn hơn 0.',
  PRODUCT_CATEGORY_MUST_BE_EMPTY: 'Danh mục sản phẩm đang có sản phẩm.'
} as const

export const ADDRESS_MESSAGES = {
  COMMUNES_ID_IS_REQUIRED: 'ID phường/xã là bắt buộc.',
  GET_COMMUNES_SUCCESS: 'Lấy danh sách phường/xã thành công.',
  GET_PROVINCES_SUCCESS: 'Lấy danh sách tỉnh/thành thành công.',
  GET_DISTRICTS_SUCCESS: 'Lấy danh sách quận/huyện thành công.',
  PROVINCE_ID_IS_REQUIRED: 'ID tỉnh/thành là bắt buộc.',
  PROVINCE_ID_IS_INVALID: 'ID tỉnh/thành không hợp lệ.',
  PROVINCE_NOT_FOUND: 'Không tìm thấy tỉnh thành.',
  GET_WARDS_SUCCESS: 'Lấy danh sách phường xã thành công.',
  CREATE_ADDRESS_SUCCESS: 'Tạo địa chỉ mới thành công.',
  ADDRESS_FULLNAME_IS_REQUIRED: 'Họ tên người nhận là bắt buộc.',
  ADDRESS_PHONE_NUMBER_IS_REQUIRED: 'Số điện thoại người nhận là bắt buộc.',
  ADDRESS_PHONE_NUMBER_IS_INVALID: 'Số điện thoại người nhận không hợp lệ.',
  ADDRESS_DETAIL_IS_REQUIRED: 'Địa chỉ cụ thể là bắt buộc.',
  ADDRESS_TYPE_IS_REQUIRED: 'Loại địa chỉ là bắt buộc.',
  ADDRESS_TYPE_IS_INVALID: 'Loại địa chỉ không hợp lệ.',
  DISTRICT_ID_IS_REQUIRED: 'ID quận/huyện là bắt buộc.',
  WARD_ID_IS_REQUIRED: 'ID phường/xã là bắt buộc.',
  GET_MY_ADDRESSES_SUCCESS: 'Lấy danh sách địa chỉ của tôi thành công.',
  ADDRESS_ID_IS_REQUIRED: 'ID địa chỉ là bắt buộc.',
  ADDRESS_ID_IS_INVALID: 'ID địa chỉ không hợp lệ.',
  ADDRESS_NOT_FOUND: 'Không tìm thấy địa chỉ.',
  GET_ADDRESS_SUCCESS: 'Lấy thông tin địa chỉ thành công.',
  UPDATE_ADDRESS_SUCCESS: 'Cập nhật địa chỉ thành công.',
  DELETE_ADDRESS_SUCCESS: 'Xóa địa chỉ thành công.',
  SET_DEFAULT_ADDRESS_SUCCESS: 'Đặt địa chỉ mặc định thành công.'
} as const

export const CART_MESSAGES = {
  ADD_PRODUCT_TO_CART_SUCCESS: 'Thêm sản phẩm vào giỏ hàng thành công.',
  QUANTITY_IS_REQUIRED: 'Số lượng là bắt buộc.',
  QUANTITY_MUST_BE_AN_INT: 'Số lượng phải là một số nguyên.',
  QUANTITY_MUST_BE_GREATER_THAN_ZERO: 'Số lượng phải lớn hơn 0.',
  GET_MY_CART_SUCCESS: 'Lấy thông tin giỏ hàng thành công.',
  UPDATE_CART_ITEM_SUCCESS: 'Cập nhật giỏ hàng thành công.',
  CART_ITEM_ID_IS_REQUIRED: 'ID mặt hàng giỏ hàng là bắt buộc.',
  CART_ITEM_ID_IS_INVALID: 'ID mặt hàng giỏ hàng không hợp lệ.',
  CART_ITEM_NOT_FOUND: 'Không tìm thấy mặt hàng giỏ hàng.',
  DELETE_CART_ITEMS_SUCCESS: 'Xóa mặt hàng trong giỏ hàng thành công.',
  CART_ITEM_IDS_IS_REQUIRED: 'ID các mặt hàng là bắt buộc.',
  CART_ITEM_IDS_MUST_BE_AN_ARRAY: 'ID các mặt hàng phải là một mảng.',
  CART_ITEM_IDS_IS_INVALID: 'ID các mặt hàng không hợp lệ.',
  CART_ITEM_IDS_MUST_NOT_BE_EMPTY: 'ID các mặt hàng phải là một mảng không rỗng.'
} as const

export const ORDER_MESSAGES = {
  CREATE_ORDER_EVENT_SUCCESS: 'Thêm sự kiện cho đơn hàng thành công',
  CANCEL_ORDER_SUCCESS: 'Hủy bỏ đơn hàng thành công.',
  CREATE_ORDER_SUCCESS: 'Đặt hàng thành công.',
  TOTAL_ITEMS_IS_REQUIRED: 'Tổng số mặt hàng là bắt buộc.',
  TOTAL_ITEMS_MUST_BE_GREATER_THAN_ZERO: 'Tổng số mặt hàng phải là số nguyên lớn hơn 0.',
  TOTAL_AMOUNT_IS_REQUIRED: 'Tổng tiền là bắt buộc.',
  TOTAL_AMOUNT_MUST_BE_GREATER_THAN_ZERO: 'Tổng tiền phải là số nguyên lớn hơn 0.',
  SELLER_ID_IS_REQUIRED: 'ID người bán là bắt buộc.',
  SELLER_ID_IS_INVALID: 'ID người bán không hợp lệ.',
  SELLER_NOT_FOUND: 'Không tìm thấy người bán.',
  CANNOT_BUY_YOUR_ITEMS: 'Bạn không thể tự mua hàng của mình.',
  GET_MY_ORDERS_SUCCESS: 'Lấy danh sách đơn hàng thành công.',
  GET_ORDER_SUCCESS: 'Lấy thông tin đơn hàng thành công.',
  ORDER_ID_IS_REQUIRED: 'ID đơn hàng là bắt buộc.',
  ORDER_ID_IS_INVALID: 'ID đơn hàng không hợp lệ.',
  ORDER_NOT_FOUND: 'Không tìm thấy đơn hàng.',
  UPDATE_ORDER_SUCCESS: 'Cập nhật đơn hàng thành công.',
  ORDER_STATUS_IS_INVALID: 'Trạng thái đơn hàng không hợp lệ.',
  GET_ALL_ORDERS_SUCCESS: 'Lấy danh sách tất cả đơn hàng thành công.',
  NOTE_MAX_LENGTH_IS_500_CHARACTERS: 'Ghi chú đơn hàng tối đa 500 ký tự.',
  SHIPPING_METHOD_IS_INVALID: 'Phương thức vận chuyển không hợp lệ.',
  ADDRESS_ID_IS_REQUIRED: 'ID địa chỉ là bắt buộc.',
  ADDRESS_ID_IS_INVALID: 'ID địa chỉ không hợp lệ.',
  ADDRESS_NOT_FOUND: 'Không tìm thấy địa chỉ.',
  SHIPPING_FEE_IS_REQUIRED: 'Phí vận chuyển là bắt buộc.',
  SHIPPING_FEE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ZERO: 'Phí vận chuyển phải là một số nguyên lớn hơn hoặc bằng 0.',
  TOTAL_DISCOUNT_MUST_BE_GREATER_THAN_OR_EQUAL_TO_ZERO: 'Tổng giảm giá phải là một số nguyên lớn hơn hoặc bằng 0.',
  ORDER_EVENT_CONTENT_IS_REQUIRED: 'Nội dung của sự kiện đơn hàng là bắt buộc.',
  GET_ORDER_EVENTS_SUCCESS: 'Lấy danh sách sự kiện của đơn hàng thành công.',
  DELETE_ORDER_EVENT_SUCCESS: 'Xóa sự kiện đơn hàng thành công.',
  ORDER_EVENT_ID_IS_REQUIRED: 'ID sự kiện đơn hàng là bắt buộc.',
  ORDER_EVENT_ID_IS_INVALID: 'ID sự kiện đơn hàng không hợp lệ.',
  ORDER_EVENT_NOT_FOUND: 'Không tìm thấy sự kiện đơn hàng.'
} as const

export const REVIEWS_MESSAGE = {
  CREATE_REVIEW_SUCCESS: 'Đánh giá sản phẩm thành công.',
  STAR_POINTS_IS_REQUIRED: 'Số sao đánh giá là bắt buộc.',
  STAR_POINTS_MUST_BE_AN_INTEGER: 'Số sao đánh giá phải là một số nguyên.',
  STAR_POINTS_IS_INVALID: 'Số sao đánh giá phải có giá trị từ 1 đến 5.',
  PHOTOS_MUST_BE_AN_ARRAY: 'Hình ảnh thực tế phải là một mảng.',
  PHOTOS_IS_INVALID: 'Hình ảnh thực tế không hợp lệ.',
  PLEASE_BUY_BEFORE_REVIEW: 'Bạn phải mua sản phẩm trước khi đánh giá.',
  YOU_HAVE_REVIEWED_BEFORE: 'Bạn đã đánh giá trước đó',
  GET_REVIEWD_PRODUCT_IDS_SUCCESS: 'Lấy danh sách ID sản phẩm đã đánh giá thành công.',
  GET_REVIEWS_SUCCESS: 'Lấy danh sách đánh giá thành công.'
} as const

export const BLOGS_MESSAGE = {
  CREATE_BLOG_SUCCESS: 'Tạo blog thành công.',
  BLOG_TITLE_IS_REQUIRED: 'Tiêu đề blog là bắt buộc.',
  BLOG_CONTENT_IS_REQUIRED: 'Nội dung blog là bắt buộc.',
  BLOG_STATUS_IS_INVALID: 'Trạng thái blog không hợp lệ.',
  BLOG_ORDER_MUST_BE_A_INT: 'Thứ tự blog phải là một số nguyên.',
  BLOG_ORDER_MUST_BE_GREATER_THAN_ZERO: 'Thứ tự blog phải lớn hơn 0.',
  UPDATE_BLOG_SUCCESS: 'Cập nhật blog thành công.',
  BLOG_ID_IS_REQUIRED: 'ID blog là bắt buộc.',
  BLOG_ID_IS_INVALID: 'ID blog không hợp lệ.',
  BLOG_NOT_FOUND: 'Không tìm thấy blog.',
  GET_BLOGS_SUCCESS: 'Lấy danh sách blog thành công.',
  GET_BLOG_SUCCESS: 'Lấy thông tin blog thành công.',
  DELETE_BLOGS_SUCCESS: 'Xóa bài viết thành công',
  BLOG_IDS_IS_REQUIRED: 'ID bài viết là bắt buộc.',
  BLOG_IDS_MUST_BE_AN_ARRAY: 'ID bài viết phải là một mảng.',
  BLOG_IDS_IS_INVALID: 'ID bài viết không hợp lệ.',
  DELETE_BLOG_SUCCESS: 'Xóa blog thành công.'
} as const
